apiVersion: v1
kind: Pod
metadata:
  name: myapp Pod
  labels:
    app: myapp
    placeholder_anylabel: location

spec:
  securityContext:
    runAsUser: 1000
  containers:
    - name: nginx-container
      image: nginx
      command: ["sleep", "3600"]
      #securityContext:
      #  runAsUser: 1000
      capabilities:
        add: ["MAC_ADMIN"]