apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: files that the kustomization needs to handle
  - nginx-deployment.yaml
  - nginx-service.yaml

//transformations to do
commonLabels:
  company: KodeKloud
namespace: nameofnamespacetochange
namePrefix:
nameSuffix: 
commonAnnotation:
  example: example

images:
  - name: nginx
    newName: haproxy
    newTag: "2.4"


patches:
 - target:
   kind: deployment
   name: api-deployment
   

   patch: |- or put a path:replica-patch.yaml
    - op: replace
      path: /spec/replicas
      value: 5