apiVersion: v1
kind: ReplicationController
metadata:
 name: myapp
 labels:
  app: myapp
  type: front-end

spec:
  template: #pod specs to duplicate

    metadata:
      name: myapp Pod
      labels:
        app: myapp
        placeholder_anylabel: location

    spec:
      containers:
        - name: nginx-container
          image: nginx

        - name: second container
          image: redis
  replicas: 3 #how many replicas