apiVersion: v1
kind: Pod
metadata:
  name: myapp Pod
  labels:
    app: myapp
    placeholder_anylabel: location

spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - container Port: 8080
  - name: app
    image: app
      