apiVersion: v1
kind: Pod
metadata:
  name: myapp Pod
  labels:
    app: myapp
    placeholder_anylabel: location

spec:
  containers:
  - name: nginx-container
    image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpression:
          - key: size
            operator: In
            values:
            - Large